<?php
require_once 'PHPUnit/Framework.php';

require_once 'Diggin/Http/Response/Encoding.php';

/**
 * Test class for Diggin_Http_Response_Encoding.
 * Generated by PHPUnit on 2008-12-11 at 21:42:20.
 */
class Diggin_Http_Response_EncodingTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Diggin_Http_Response_Encoding
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = new Diggin_Http_Response_Encoding;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testEncode().
     */
    public function testEncode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testEncodeResponseObject().
     */
    public function testEncodeResponseObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * test "detect" part.1
     * 
     * @todo Implement testDetect().
     */
    public function testDetectOnlyResponseBody() {
        //
        $this->assertEquals('Shift_JIS',
                            $this->object->detect(pack("C2", 0x87, 0x40)));

        //@see http://homepage2.nifty.com/Catra/memo/perl_pack.html
        $this->assertEquals('EUC-JP',
                            $this->object->detect(pack("C4", 164, 164, 164, 164)));
    }
    
    /**
     * test "detect" part.2 
     * 
     * @todo Implement testDetect().
     */
    public function testDetectWithContentType() {
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
